name: Build and Deploy MKT Adobe

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
  # workflow_dispatch:

jobs:
  build:
    name: Build and Deploy SSIS Package
   # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build SSIS Package
        run: 
          powershell -File build.ps1
